server.port=8080
spring.application.name=PDF Converter Application

# File upload settings
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Logging
logging.level.root=INFO
logging.level.com.pm.pdfconverterapplication=DEBUG

# OpenAI API Configuration
# ADD YOUR OPENAI API KEY HERE: https://platform.openai.com/api-keys
openai.api.key=sk-add-your-openai-api-key-here
openai.model=gpt-3.5-turbo


